### ISSUE TITLE
What dashboard?

### ISSUE THREAD

**Issue by legionglobal** [surjithctly/web3forms-docs#17]
The documentation for integrating Cloudflare Turnstile specifically states that there's a dashboard to add your secret key to in order to get Turnstile to work with Web3Forms:

https://docs.web3forms.com/getting-started/pro-features/cloudflare-turnstile-captcha

```
4. Add Secret Keys to your Web3Forms Dashboard
- Visit the Web3Forms Dashboard and select your form. 
- Open Settings and choose turnstile as your captcha provider
- Enter the Secret Key in the Textbox below
- Save Changes
```

My question is, where?

**Comment by surjithctly** [comment]
Hi, The dashboard is in beta right now. Could you share the details via support @ web3forms dot com while we open this up to public?
